name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.13
      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.1.0
      - name: Build Project
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          build-root-directory: server
          wrapper-directory: server
      
